import java.io.*;
import java.net.*;
import java.lang.instrument.Instrumentation;
import java.lang.reflect.*;
import java.util.*;
import java.util.concurrent.*;
import javax.swing.*;
import javax.imageio.ImageIO;
import java.awt.image.BufferedImage;
import java.awt.Graphics2D;
import java.awt.Color;
import java.awt.RenderingHints;
import com.sun.net.httpserver.HttpServer;
import com.cburch.logisim.proj.*;
import com.cburch.logisim.file.*;
import com.cburch.logisim.circuit.*;
import com.cburch.logisim.comp.*;
import com.cburch.logisim.data.*;
import com.cburch.logisim.instance.*;
import com.cburch.logisim.std.wiring.Pin;
import com.cburch.logisim.tools.*;
import com.cburch.logisim.analyze.model.*;
import com.cburch.logisim.std.gates.CircuitBuilder;

/** Versioned in-process adapter for classic Logisim 2.7.1. All model work runs on EDT. */
public class Workbench extends LiveBridge {
 static final String BUILD="BUILD_ID";
 static final Map<String,Object> objects=new LinkedHashMap<>();
 static final IdentityHashMap<Object,String> handles=new IdentityHashMap<>();
 static int sequence=0;
 static final Map<String,Executable> methods=new LinkedHashMap<>();
 static final Map<String,Field> fields=new LinkedHashMap<>();
 static final Map<String,AnalyzerModel> analyzers=new LinkedHashMap<>();
 static final Map<String,Object> logs=new LinkedHashMap<>();
 static void settle(Project p,boolean tick)throws Exception {
  Simulator sim=p.getSimulator();boolean running=sim.isRunning();
  Field field=Simulator.class.getDeclaredField("manager");field.setAccessible(true);Thread manager=(Thread)field.get(sim);
  Field requested=manager.getClass().getDeclaredField("propagateRequested");requested.setAccessible(true);
  CountDownLatch finished=new CountDownLatch(1);int target=p.getCircuitState().getPropagator().getTickCount()+(tick?1:0);
  java.util.concurrent.atomic.AtomicBoolean armed=new java.util.concurrent.atomic.AtomicBoolean(false);
  SimulatorListener listener=new SimulatorListener(){public void propagationCompleted(SimulatorEvent event){synchronized(manager){try{if(armed.get()&&p.getCircuitState().getPropagator().getTickCount()>=target&&!requested.getBoolean(manager))finished.countDown();}catch(Exception ignored){}}}public void tickCompleted(SimulatorEvent event){}public void simulatorStateChanged(SimulatorEvent event){}};
  sim.addSimulatorListener(listener);
  try{sim.setIsRunning(true);synchronized(manager){armed.set(true);if(tick)sim.tick();else sim.requestPropagate();}if(!finished.await(10,TimeUnit.SECONDS))throw new IllegalStateException("Native simulator did not settle within 10 seconds");if(sim.isExceptionEncountered())throw new IllegalStateException("Native simulator reported an exception");}
  finally{sim.removeSimulatorListener(listener);if(!running)sim.setIsRunning(false);}
 }
 static Object map(Object... kv){Map<String,Object> m=new LinkedHashMap<>();for(int i=0;i<kv.length;i+=2)m.put(kv[i].toString(),kv[i+1]);return m;}
 static String str(Map a,String key){Object v=a.get(key);if(v==null)throw new IllegalArgumentException("Missing "+key);return v.toString();}
 static int integer(Map a,String key,int def){return a.containsKey(key)?((Number)a.get(key)).intValue():def;}
 static boolean bool(Map a,String key,boolean def){return a.containsKey(key)?Boolean.TRUE.equals(a.get(key)):def;}
 static String ref(Object o){if(o==null)return null;String id=handles.get(o);if(id==null){id="o"+(++sequence);handles.put(o,id);objects.put(id,o);}return id;}
 static Object object(String id){if(!objects.containsKey(id))throw new IllegalArgumentException("Expired/unknown handle "+id);return objects.get(id);}
 static Object value(Object o){
  if(o==null||o instanceof String||o instanceof Number||o instanceof Boolean)return o;
  if(o instanceof Character)return o.toString();
  if(o instanceof Value)return map("binary",((Value)o).toDisplayString(2),"width",((Value)o).getWidth(),"defined",((Value)o).isFullyDefined(),"unsigned",((Value)o).isFullyDefined()?Integer.toUnsignedLong(((Value)o).toIntValue()):null);
  return map("ref",ref(o),"class",o.getClass().getName());
 }
 public static void premain(String args,Instrumentation instrumentation)throws Exception {agentmain(args,instrumentation);}
 public static void agentmain(String args,Instrumentation instrumentation)throws Exception {
  if(server!=null)server.stop(0);
  int port;
  if(args.startsWith("@")) {
   File optionsFile=args.startsWith("@uri:")?new File(new URI(args.substring(5))):new File(args.substring(1));
   Map options=(Map)Json.parse(new String(java.nio.file.Files.readAllBytes(optionsFile.toPath()),"UTF-8"));
   port=((Number)options.get("port")).intValue();token=String.valueOf(options.get("token"));workspace=new File(String.valueOf(options.get("workspace"))).getCanonicalFile();
  } else {String[] a=args.split("\\|",3);port=Integer.parseInt(a[0]);token=a[1];workspace=new File(a[2]).getCanonicalFile();}
  server=HttpServer.create(new InetSocketAddress("127.0.0.1",port),0);
  server.createContext("/",e->{
   if(!token.equals(e.getRequestHeaders().getFirst("X-Logisim-Token"))){e.sendResponseHeaders(403,-1);e.close();return;}
   if(!e.getRequestMethod().equals("POST")){e.sendResponseHeaders(405,-1);e.close();return;}
   int code=200;String response;
   try {
    ByteArrayOutputStream b=new ByteArrayOutputStream();byte[] buffer=new byte[8192];int n;while((n=e.getRequestBody().read(buffer))!=-1){if(b.size()+n>1048576)throw new IOException("Request exceeds 1 MiB");b.write(buffer,0,n);}
    String data=new String(b.toByteArray(),"UTF-8");String endpoint=e.getRequestURI().getPath();
    FutureTask<String> task=new FutureTask<>(()->{if(endpoint.equals("/health"))return Json.write(map("build",BUILD,"version","2.7.1","workspace",workspace.getPath()));if(endpoint.equals("/v3"))return Json.write(execute((Map)Json.parse(data)));return command(endpoint,data);});
    SwingUtilities.invokeLater(task);response=task.get(55,TimeUnit.SECONDS);
   } catch(Exception ex){code=400;Throwable cause=ex;while(cause.getCause()!=null)cause=cause.getCause();response=Json.write(map("error",cause.getClass().getSimpleName(),"message",String.valueOf(cause.getMessage()),"stack",Arrays.asList(cause.getStackTrace()).subList(0,Math.min(8,cause.getStackTrace().length))));}
   byte[] body=response.getBytes("UTF-8");e.getResponseHeaders().set("Content-Type","application/json; charset=utf-8");e.sendResponseHeaders(code,body.length);e.getResponseBody().write(body);e.close();
  });server.setExecutor(Executors.newCachedThreadPool(r->{Thread t=new Thread(r,"Logisim MCP");t.setDaemon(true);return t;}));server.start();
 }
 static Project project(Map a){String name=str(a,"project");if(objects.get(name) instanceof Project)return (Project)objects.get(name);List<Project> matches=new ArrayList<>();for(Project p:Projects.getOpenProjects())if(p.getLogisimFile().getName().equals(name))matches.add(p);if(matches.size()!=1)throw new IllegalArgumentException("Use unique project name or project ref from projects");return matches.get(0);}
 static File path(String name,boolean newFile)throws IOException{File f=new File(name).getCanonicalFile();if(!f.toPath().startsWith(workspace.toPath()))throw new IllegalArgumentException("Path outside workspace");if(newFile&&f.exists())throw new IllegalArgumentException("Target already exists; choose new path");return f;}
 static Object attributeData(AttributeSet as){List<Object> result=new ArrayList<>();for(Attribute at:as.getAttributes()){Map item=(Map)map("name",at.getName(),"type",at.getClass().getName(),"read_only",as.isReadOnly(at));try{item.put("value",at.toStandardString(as.getValue(at)));}catch(Exception ex){item.put("value",value(as.getValue(at)));}result.add(item);}return result;}
 static Object componentData(Project p,Component c){List<Object> ports=new ArrayList<>();int i=0;for(EndData e:c.getEnds())ports.add(map("index",i++,"x",e.getLocation().getX(),"y",e.getLocation().getY(),"width",e.getWidth().getWidth(),"input",e.isInput(),"output",e.isOutput(),"value",value(p.getCircuitState().getValue(e.getLocation()))));return map("id",id(c),"ref",ref(c),"factory",c.getFactory().getName(),"factory_ref",ref(c.getFactory()),"x",c.getLocation().getX(),"y",c.getLocation().getY(),"attributes",attributeData(c.getAttributeSet()),"ports",ports);}
 static Component comp(Project p,String id){Object o=objects.get(id);if(o instanceof Component&&p.getCurrentCircuit().contains((Component)o))return (Component)o;return find(p,id);}
 static Component make(Project p,Map a){ComponentFactory f=factory(p,str(a,"library"),str(a,"component"));AttributeSet as=f.createAttributeSet();Map<String,Object> at=(Map)a.getOrDefault("attributes",Collections.emptyMap());
  // Shape-changing attributes precede dependent bit/negation assignments.
  for(String k:Arrays.asList("inputs","width","fanout","incoming","addrWidth","dataWidth"))if(at.containsKey(k))set(as,k,String.valueOf(at.get(k)));
  for(String k:at.keySet())if(!Arrays.asList("inputs","width","fanout","incoming","addrWidth","dataWidth").contains(k))set(as,k,String.valueOf(at.get(k)));
  int x=integer(a,"x",0),y=integer(a,"y",0);if(x%10!=0||y%10!=0)throw new IllegalArgumentException("Coordinates must align to 10-pixel grid");Component cp=f.createComponent(Location.create(x,y),as);if(p.getCurrentCircuit().hasConflict(cp))throw new IllegalArgumentException("Component conflicts at "+cp.getLocation());return cp;
 }
 static AnalyzerModel model(Map a){String id=str(a,"analyzer");if(!analyzers.containsKey(id))throw new IllegalArgumentException("Unknown analyzer");return analyzers.get(id);}
 static Object tableData(AnalyzerModel m){TruthTable t=m.getTruthTable();List<Object> rows=new ArrayList<>();for(int r=0;r<t.getRowCount();r++){StringBuilder in=new StringBuilder(),out=new StringBuilder();for(int j=0;j<t.getInputColumnCount();j++)in.append(t.getInputEntry(r,j).getDescription());for(int j=0;j<t.getOutputColumnCount();j++)out.append(t.getOutputEntry(r,j).getDescription());rows.add(map("input",in.toString(),"output",out.toString()));}List<Object> exp=new ArrayList<>();for(String s:m.getOutputs().getAll())exp.add(map("output",s,"expression",m.getOutputExpressions().getExpressionString(s),"minimal",String.valueOf(m.getOutputExpressions().getMinimalExpression(s)),"format",m.getOutputExpressions().getMinimizedFormat(s)));return map("analyzer",ref(m),"inputs",m.getInputs().getAll(),"outputs",m.getOutputs().getAll(),"rows",rows,"expressions",exp);}
 static Object invoke(Object target,String method,Class[] types,Object... arguments)throws Exception{Class c=target instanceof Class?(Class)target:target.getClass();Method m=null;for(Class k=c;k!=null&&m==null;k=k.getSuperclass())try{m=k.getDeclaredMethod(method,types);}catch(NoSuchMethodException ignored){}if(m==null)m=c.getMethod(method,types);m.setAccessible(true);return m.invoke(target instanceof Class?null:target,arguments);}
 static Object contents(Project p,Component cp)throws Exception{if(cp.getFactory().getName().equals("ROM"))return cp.getAttributeSet().getValue(cp.getAttributeSet().getAttribute("contents"));if(!cp.getFactory().getName().equals("RAM"))throw new IllegalArgumentException("Expected RAM or ROM");Object s=invoke(cp.getFactory(),"getState",new Class[]{InstanceState.class},p.getCircuitState().getInstanceState(cp));return invoke(s,"getContents",new Class[]{});}

 static Object execute(Map a)throws Exception {
  String op=str(a,"op");
  if(op.equals("projects")){List<Object> out=new ArrayList<>();for(Project p:Projects.getOpenProjects())out.add(map("ref",ref(p),"name",p.getLogisimFile().getName(),"circuit",p.getCurrentCircuit().getName(),"dirty",p.isFileDirty(),"file",String.valueOf(p.getLogisimFile().getLoader().getMainFile())));return out;}
  if(op.equals("new_project")){Project p=ProjectActions.doNew((Project)null);p.getLogisimFile().setName(str(a,"name"));return value(p);}
  if(op.equals("open")){File f=path(str(a,"path"),false);if(!f.getName().endsWith(".circ")||!f.isFile())throw new IllegalArgumentException("Expected existing .circ file");return value(ProjectActions.doOpen(null,null,f));}
  if(op.equals("windows")){List<Object> out=new ArrayList<>();for(java.awt.Window w:java.awt.Window.getWindows())if(w.isDisplayable())out.add(widget(w,0,integer(a,"depth",6)));return out;}
  if(op.equals("widget")){Object obj=object(str(a,"ref"));String action=str(a,"action");if(action.equals("click")&&obj instanceof AbstractButton){if(!((AbstractButton)obj).isEnabled())throw new IllegalArgumentException("Button disabled");SwingUtilities.invokeLater(()->((AbstractButton)obj).doClick());return map("queued",true);}if(action.equals("text")&&obj instanceof javax.swing.text.JTextComponent){((javax.swing.text.JTextComponent)obj).setText(str(a,"value"));return true;}if(action.equals("select")&&obj instanceof JComboBox){((JComboBox)obj).setSelectedIndex(integer(a,"index",0));return true;}if(action.equals("select")&&obj instanceof JTabbedPane){((JTabbedPane)obj).setSelectedIndex(integer(a,"index",0));return true;}if(action.equals("select")&&obj instanceof JList){((JList)obj).setSelectedIndex(integer(a,"index",0));return true;}if(action.equals("spinner")&&obj instanceof JSpinner){((JSpinner)obj).setValue(a.get("value"));return true;}if(action.equals("front")&&obj instanceof java.awt.Window){((java.awt.Window)obj).toFront();return true;}throw new IllegalArgumentException("Unsupported widget/action combination");}
  if(op.startsWith("api_"))return api(a);
  Project p=project(a);Circuit c=p.getCurrentCircuit();CircuitState state=p.getCircuitState();
  if(op.equals("close")){if(p.isFileDirty()&&!bool(a,"discard_changes",false))throw new IllegalArgumentException("Project has unsaved changes; save first or explicitly discard_changes");if(Projects.getOpenProjects().size()<=1)throw new IllegalArgumentException("Last project: use the native Close/Exit menu if you intend to exit Logisim");String name=p.getLogisimFile().getName();p.getFrame().dispose();return map("closed",name);}
  if(op.equals("roots"))return map("project",value(p),"file",value(p.getLogisimFile()),"loader",value(p.getLogisimFile().getLoader()),"circuit",value(c),"state",value(state),"simulator",value(p.getSimulator()),"appearance",value(c.getAppearance()),"selection",value(p.getSelection()),"options",value(p.getOptions()),"frame",value(p.getFrame()),"canvas",value(p.getFrame().getCanvas()));
  if(op.equals("catalog")){List<Object> libs=new ArrayList<>();for(Library lib:p.getLogisimFile().getLibraries()){List<Object> ts=new ArrayList<>();for(Tool t:lib.getTools()){Map info=(Map)map("name",t.getName(),"ref",ref(t),"component",t instanceof AddTool);if(t instanceof AddTool){ComponentFactory f=((AddTool)t).getFactory();info.put("factory_ref",ref(f));info.put("attributes",attributeData(f.createAttributeSet()));}ts.add(info);}libs.add(map("name",lib.getName(),"ref",ref(lib),"tools",ts));}return libs;}
  if(op.equals("snapshot")){List<Object> cs=new ArrayList<>(),ws=new ArrayList<>();for(Component cp:c.getNonWires())cs.add(componentData(p,cp));for(Wire w:c.getWires())ws.add(map("ref",ref(w),"from",Arrays.asList(w.getEnd0().getX(),w.getEnd0().getY()),"to",Arrays.asList(w.getEnd1().getX(),w.getEnd1().getY()),"value",value(state.getValue(w.getEnd0()))));return map("circuit",c.getName(),"components",cs,"wires",ws,"width_conflicts",(c.getWidthIncompatibilityData()==null?0:c.getWidthIncompatibilityData().size()),"oscillating",state.getPropagator().isOscillating());}
  if(op.equals("component"))return componentData(p,comp(p,str(a,"id")));
  if(op.equals("edit")){
   CircuitMutation m=new CircuitMutation(c);List<Object> created=new ArrayList<>();List<Component> staged=new ArrayList<>();
   for(Map cmd:(List<Map>)a.get("actions")){
    String kind=str(cmd,"kind");
    if(kind.equals("add")){Component cp=make(p,cmd);for(Component prior:staged)if(prior.getLocation().equals(cp.getLocation()))throw new IllegalArgumentException("Duplicate location in batch");staged.add(cp);m.add(cp);created.add(map("id",id(cp),"ref",ref(cp)));}
    else if(kind.equals("wire")){List<List<Number>> pts=(List)cmd.get("points");if(pts.size()<2)throw new IllegalArgumentException("Wire requires two points");Location prev=null;for(List<Number> pt:pts){Location next=Location.create(pt.get(0).intValue(),pt.get(1).intValue());if(next.getX()%10!=0||next.getY()%10!=0)throw new IllegalArgumentException("Wire off grid");if(prev!=null&&!prev.equals(next)){if(prev.getX()!=next.getX()&&prev.getY()!=next.getY())throw new IllegalArgumentException("Diagonal wire");m.add(Wire.create(prev,next));}prev=next;}}
    else if(kind.equals("remove_wire")){List<Number> start=(List)cmd.get("from"),end=(List)cmd.get("to");Wire w=Wire.create(Location.create(start.get(0).intValue(),start.get(1).intValue()),Location.create(end.get(0).intValue(),end.get(1).intValue()));if(!c.getWires().contains(w))throw new IllegalArgumentException("Exact wire segment not found");m.remove(w);}
    else {Component cp=comp(p,str(cmd,"id"));if(kind.equals("remove"))m.remove(cp);else if(kind.equals("attribute")){AttributeSet as=(AttributeSet)cp.getAttributeSet().clone();String key=str(cmd,"key");set(as,key,str(cmd,"value"));m.set(cp,as.getAttribute(key),as.getValue(as.getAttribute(key)));}else if(kind.equals("move")||kind.equals("duplicate")){Component next=cp.getFactory().createComponent(Location.create(integer(cmd,"x",0),integer(cmd,"y",0)),(AttributeSet)cp.getAttributeSet().clone());if(c.hasConflict(next))throw new IllegalArgumentException("Move/copy conflicts");if(kind.equals("move"))m.remove(cp);m.add(next);created.add(map("id",id(next),"ref",ref(next)));}else throw new IllegalArgumentException("Unknown edit kind "+kind);}
   }
   apply(p,m);return map("created",created,"undoable",true);
  }
  if(op.equals("pins")){
   Map<String,Component> pinmap=new LinkedHashMap<>();for(Component cp:c.getNonWires())if(cp.getFactory() instanceof Pin){String label=cp.getAttributeSet().getValue(StdAttr.LABEL);if(pinmap.put(label,cp)!=null)throw new IllegalArgumentException("Duplicate pin label: "+label);}
   Map<String,Object> inputs=(Map)a.getOrDefault("values",Collections.emptyMap());Map<Component,Value> pending=new LinkedHashMap<>();for(String name:inputs.keySet()){
    Component cp=pinmap.get(name);if(cp==null||!Circuit.isInput(cp))throw new IllegalArgumentException("Input not found: "+name);int width=cp.getEnd(0).getWidth().getWidth();Object raw=inputs.get(name);Value val;
    if(raw instanceof Number){long n=((Number)raw).longValue();if(n<0||n>=(1L<<width))throw new IllegalArgumentException("Input out of range");val=Value.createKnown(BitWidth.create(width),(int)n);}else {String bits=raw.toString().replace(" ","");if(bits.length()!=width||!bits.matches("[01xE]+"))throw new IllegalArgumentException("Expected exact-width binary string with 0,1,x,E");Value[] vs=new Value[width];for(int i=0;i<width;i++){char ch=bits.charAt(width-1-i);vs[i]=ch=='1'?Value.TRUE:ch=='0'?Value.FALSE:ch=='x'?Value.UNKNOWN:Value.ERROR;}val=Value.create(vs);}pending.put(cp,val);
   }for(Map.Entry<Component,Value> entry:pending.entrySet()){Pin.FACTORY.setValue(state.getInstanceState(entry.getKey()),entry.getValue());state.markComponentAsDirty(entry.getKey());}
   if(!pending.isEmpty())settle(p,false);p.repaintCanvas();Map<String,Object> result=new LinkedHashMap<>();for(String name:pinmap.keySet()){Component cp=pinmap.get(name);result.put(name,map("input",Circuit.isInput(cp),"value",value(Pin.FACTORY.getValue(state.getInstanceState(cp)))));}return result;
  }
  if(op.equals("probe"))return value(state.getValue(Location.create(integer(a,"x",0),integer(a,"y",0))));
  if(op.equals("undo")){p.undoAction();return map("undone",true);}
  if(op.equals("simulate")){Simulator sim=p.getSimulator();String action=(String)a.getOrDefault("action","status");if(action.equals("propagate"))settle(p,false);else if(action.equals("tick"))settle(p,true);else if(action.equals("step"))sim.step();else if(action.equals("reset"))sim.requestReset();else if(action.equals("run"))sim.setIsRunning(true);else if(action.equals("pause"))sim.setIsRunning(false);else if(action.equals("ticks_on"))sim.setIsTicking(true);else if(action.equals("ticks_off"))sim.setIsTicking(false);else if(action.equals("frequency")){double hz=((Number)a.get("hz")).doubleValue();if(hz<=0||hz>4096)throw new IllegalArgumentException("0 < Hz <= 4096");sim.setTickFrequency(hz);}else if(!action.equals("status"))throw new IllegalArgumentException("Unknown simulation action");return map("running",sim.isRunning(),"ticking",sim.isTicking(),"frequency",sim.getTickFrequency(),"oscillating",sim.isOscillating(),"exception",sim.isExceptionEncountered(),"async",action.equals("step")||action.equals("reset"));}
  if(op.equals("ticks")){int count=integer(a,"count",1);if(count<0||count>10000)throw new IllegalArgumentException("0..10000 ticks");if(p.getSimulator().isTicking())throw new IllegalArgumentException("Disable automatic ticks before deterministic stepping");for(int i=0;i<count;i++){settle(p,true);}p.repaintCanvas();return map("ticks",count,"total_ticks",state.getPropagator().getTickCount(),"oscillating",state.getPropagator().isOscillating());}
  if(op.equals("statistics")){FileStatistics stats=FileStatistics.compute(p.getLogisimFile(),c);List<Object> out=new ArrayList<>();for(Object item:stats.getCounts()){Map<String,Object> v=new LinkedHashMap<>();for(Field field:item.getClass().getDeclaredFields())if(!field.isSynthetic()){field.setAccessible(true);v.put(field.getName(),value(field.get(item)));}out.add(v);}return map("counts",out,"native_ref",ref(stats));}
  if(op.equals("selection")){String action=str(a,"action");com.cburch.logisim.gui.main.Selection sel=p.getSelection();if(action.equals("select")){p.doAction(com.cburch.logisim.gui.main.SelectionActions.dropAll(sel));for(String id:(List<String>)a.get("components"))sel.add(comp(p,id));}else if(action.equals("copy"))p.doAction(com.cburch.logisim.gui.main.SelectionActions.copy(sel));else if(action.equals("cut"))p.doAction(com.cburch.logisim.gui.main.SelectionActions.cut(sel));else if(action.equals("paste")){com.cburch.logisim.proj.Action x=com.cburch.logisim.gui.main.SelectionActions.pasteMaybe(p,sel);if(x!=null)p.doAction(x);}else if(action.equals("drop"))p.doAction(com.cburch.logisim.gui.main.SelectionActions.dropAll(sel));else if(action.equals("duplicate"))p.doAction(com.cburch.logisim.gui.main.SelectionActions.duplicate(sel));else if(action.equals("delete"))p.doAction(com.cburch.logisim.gui.main.SelectionActions.clear(sel));else if(action.equals("move"))p.doAction(com.cburch.logisim.gui.main.SelectionActions.translate(sel,integer(a,"dx",0),integer(a,"dy",0),null));else if(!action.equals("read"))throw new IllegalArgumentException("Unknown selection action");List<Object> out=new ArrayList<>();for(Component cp:sel.getComponents())out.add(value(cp));return out;}
  if(op.equals("preferences")){Map<String,Object> out=new LinkedHashMap<>();Class klass=com.cburch.logisim.prefs.AppPreferences.class;for(Field field:klass.getDeclaredFields())if(Modifier.isStatic(field.getModifiers())&&com.cburch.logisim.prefs.PrefMonitor.class.isAssignableFrom(field.getType())){field.setAccessible(true);com.cburch.logisim.prefs.PrefMonitor monitor=(com.cburch.logisim.prefs.PrefMonitor)field.get(null);if(field.getName().equals(a.get("key"))){Object old=monitor.get(),raw=a.get("value");if(old instanceof Integer)raw=((Number)raw).intValue();else if(old instanceof Double)raw=((Number)raw).doubleValue();else if(old!=null&&!old.getClass().isInstance(raw))throw new IllegalArgumentException("Preference type mismatch");monitor.set(raw);}out.put(field.getName(),monitor.get());}if(a.containsKey("key")&&!out.containsKey(a.get("key")))throw new IllegalArgumentException("Unknown preference");return out;}
  if(op.equals("circuit")){String action=str(a,"action");String name=(String)a.getOrDefault("name",c.getName());Circuit target=p.getLogisimFile().getCircuit(name);
   if(action.equals("list")){List<Object> out=new ArrayList<>();for(Circuit cc:p.getLogisimFile().getCircuits())out.add(map("name",cc.getName(),"ref",ref(cc),"main",cc==p.getLogisimFile().getMainCircuit(),"active",cc==c,"attributes",attributeData(cc.getStaticAttributes())));return out;}
   if(action.equals("add")){if(target!=null)throw new IllegalArgumentException("Circuit exists");target=new Circuit(name);p.doAction(LogisimFileActions.addCircuit(target));p.setCurrentCircuit(target);}
   else {if(target==null)throw new IllegalArgumentException("Circuit absent");if(action.equals("select"))p.setCurrentCircuit(target);else if(action.equals("main"))p.doAction(LogisimFileActions.setMainCircuit(target));else if(action.equals("remove")){if(p.getLogisimFile().getCircuitCount()<=1||!target.getCircuitsUsingThis().isEmpty())throw new IllegalArgumentException("Circuit in use or last circuit");p.doAction(LogisimFileActions.removeCircuit(target));}else if(action.equals("move"))p.doAction(LogisimFileActions.moveCircuit(p.getLogisimFile().getAddTool(target),integer(a,"index",0)));else if(action.equals("attribute")){CircuitMutation m=new CircuitMutation(target);AttributeSet attrs=(AttributeSet)target.getStaticAttributes().clone();String key=str(a,"key");set(attrs,key,str(a,"value"));m.setForCircuit(attrs.getAttribute(key),attrs.getValue(attrs.getAttribute(key)));apply(p,m);}else throw new IllegalArgumentException("Unknown circuit action");}return map("active",p.getCurrentCircuit().getName(),"count",p.getLogisimFile().getCircuitCount());
  }
  if(op.equals("save")){File f=path(str(a,"path"),!bool(a,"overwrite",false));if(!f.getName().endsWith(".circ"))throw new IllegalArgumentException("Expected .circ extension");if(f.exists()){File backup=new File(f.getPath()+".backup-"+System.currentTimeMillis());java.nio.file.Files.copy(f.toPath(),backup.toPath());}if(!p.getLogisimFile().getLoader().save(p.getLogisimFile(),f))throw new IOException("Save failed");p.setFileAsClean();return map("path",f.getPath(),"size",f.length());}
  if(op.equals("analyzer_new")){AnalyzerModel m=new AnalyzerModel();List<String> in=(List)a.get("inputs"),out=(List)a.get("outputs");if(in.size()>8||out.size()>8)throw new IllegalArgumentException("At most eight inputs and eight outputs");Set<String> seen=new HashSet<>();for(String s:in)if(!s.matches("[A-Za-z_][A-Za-z_0-9]*")||!seen.add(s))throw new IllegalArgumentException("Invalid or duplicate identifier");for(String s:out)if(!s.matches("[A-Za-z_][A-Za-z_0-9]*")||!seen.add(s))throw new IllegalArgumentException("Invalid or duplicate identifier");m.setVariables(in,out);String id=ref(m);analyzers.put(id,m);return value(m);}
  if(op.equals("analyzer_from_circuit")){SortedMap<Instance,String> labels=Analyze.getPinLabels(c);List<String> in=new ArrayList<>(),out=new ArrayList<>();for(Map.Entry<Instance,String> e:labels.entrySet()){if(Pin.FACTORY.getWidth(e.getKey()).getWidth()!=1)throw new IllegalArgumentException("Analyzer needs one-bit pins");(Pin.FACTORY.isInputPin(e.getKey())?in:out).add(e.getValue());}if(in.size()>8||out.size()>8)throw new IllegalArgumentException("Analyzer maximum 8 pins per direction");AnalyzerModel m=new AnalyzerModel();m.setVariables(in,out);m.setCurrentCircuit(p,c);Analyze.computeTable(m,p,c,labels);if(bool(a,"derive_expression",true))try{Analyze.computeExpression(m,c,labels);}catch(Exception ignored){}analyzers.put(ref(m),m);return tableData(m);}
  if(op.startsWith("analyzer_")){AnalyzerModel m=model(a);
   if(op.equals("analyzer_expression")){String output=str(a,"output");if(!m.getOutputs().contains(output))throw new IllegalArgumentException("Unknown output");Expression expr=Parser.parse(str(a,"expression"),m);m.getOutputExpressions().setExpression(output,expr);}
   else if(op.equals("analyzer_table")){Map<String,List<String>> columns=(Map)a.get("columns");Map<String,Entry[]> parsed=new LinkedHashMap<>();for(String output:columns.keySet()){if(!m.getOutputs().contains(output))throw new IllegalArgumentException("Unknown output");List<String> entries=columns.get(output);if(entries.size()!=m.getTruthTable().getRowCount())throw new IllegalArgumentException("Wrong row count");Entry[] values=new Entry[entries.size()];for(int i=0;i<values.length;i++){String ch=entries.get(i);if(!Arrays.asList("0","1","x").contains(ch))throw new IllegalArgumentException("Expected 0,1,x");values[i]=Entry.parse(ch);}parsed.put(output,values);}for(String s:parsed.keySet())m.getTruthTable().setOutputColumn(m.getOutputs().indexOf(s),parsed.get(s));}
   else if(op.equals("analyzer_minimize")){int fmt=str(a,"format").equals("pos")?AnalyzerModel.FORMAT_PRODUCT_OF_SUMS:AnalyzerModel.FORMAT_SUM_OF_PRODUCTS;for(String output:m.getOutputs().getAll()){m.getOutputExpressions().setMinimizedFormat(output,fmt);if(bool(a,"apply",false))m.getOutputExpressions().setExpression(output,m.getOutputExpressions().getMinimalExpression(output));}}
   else if(op.equals("analyzer_build")){String name=str(a,"name");if(p.getLogisimFile().getCircuit(name)!=null)throw new IllegalArgumentException("Use a new circuit name");Circuit target=new Circuit(name);CircuitMutation mtn=CircuitBuilder.build(target,m,bool(a,"two_input",false),bool(a,"nand_only",false));p.doAction(LogisimFileActions.addCircuit(target));apply(p,mtn);p.setCurrentCircuit(target);return map("circuit",name,"components",target.getNonWires().size());}
   else if(!op.equals("analyzer_read"))throw new IllegalArgumentException("Unknown analyzer op");return tableData(m);
  }
  if(op.equals("memory")){Component cp=comp(p,str(a,"id"));Object mem=contents(p,cp);String action=str(a,"action");long start=integer(a,"start",0),last=((Number)invoke(mem,"getLastOffset",new Class[]{})).longValue();int width=((Number)invoke(mem,"getValueWidth",new Class[]{})).intValue();if(start<0||start>last)throw new IllegalArgumentException("Address out of range");
   if(action.equals("write")){List<Number> vals=(List)a.get("values");if(vals.size()>65536||start+vals.size()-1>last)throw new IllegalArgumentException("Write range outside memory");for(Number n:vals)if(n.longValue()<0||n.longValue()>=(1L<<width))throw new IllegalArgumentException("Word exceeds width");for(int i=0;i<vals.size();i++)invoke(mem,"set",new Class[]{long.class,int.class},start+i,vals.get(i).intValue());state.markComponentAsDirty(cp);settle(p,false);p.repaintCanvas();if(cp.getFactory().getName().equals("ROM"))p.getLogisimFile().setDirty(true);}
   else if(!action.equals("read"))throw new IllegalArgumentException("Expected read or write");int count=integer(a,"count",16);if(count<0||count>65536||start+count-1>last)throw new IllegalArgumentException("Read range outside memory");List<Object> vals=new ArrayList<>();for(int i=0;i<count;i++)vals.add(Integer.toUnsignedLong(((Number)invoke(mem,"get",new Class[]{long.class},start+i)).intValue()));return map("start",start,"last_address",last,"width",width,"values",vals,"contents_ref",ref(mem));
  }
  if(op.equals("export")){File f=path(str(a,"path"),!bool(a,"overwrite",false));double scale=((Number)a.getOrDefault("scale",2)).doubleValue();if(scale<=0||scale>8)throw new IllegalArgumentException("0 < scale <= 8");Bounds bounds=c.getBounds();int w=(int)Math.ceil((bounds.getWidth()+40)*scale),h=(int)Math.ceil((bounds.getHeight()+40)*scale);if((long)w*h>40000000)throw new IllegalArgumentException("Image exceeds 40 megapixels");BufferedImage im=new BufferedImage(Math.max(w,1),Math.max(h,1),BufferedImage.TYPE_INT_RGB);Graphics2D g=im.createGraphics();g.setColor(Color.WHITE);g.fillRect(0,0,w,h);g.setColor(Color.BLACK);g.scale(scale,scale);g.translate(20-bounds.getX(),20-bounds.getY());g.setRenderingHint(RenderingHints.KEY_ANTIALIASING,RenderingHints.VALUE_ANTIALIAS_ON);ComponentDrawContext ctx=new ComponentDrawContext(p.getFrame().getCanvas(),c,state,g,g,bool(a,"printer_view",true));ctx.setShowState(bool(a,"show_state",true));c.draw(ctx,Collections.emptySet());g.dispose();String format=(String)a.getOrDefault("format","png");if(!Arrays.asList("png","gif","jpg").contains(format)||!ImageIO.write(im,format,f))throw new IllegalArgumentException("Unsupported image format");return map("path",f.getPath(),"width",w,"height",h);}
  if(op.equals("options")){AttributeSet attrs=p.getOptions().getAttributeSet();if(a.containsKey("key")){set(attrs,str(a,"key"),str(a,"value"));p.getLogisimFile().setDirty(true);}return attributeData(attrs);}
  if(op.equals("library")){String action=str(a,"action");if(action.equals("load")){File file=path(str(a,"path"),false);Library lib;if(file.getName().endsWith(".circ"))lib=p.getLogisimFile().getLoader().loadLogisimLibrary(file);else if(file.getName().endsWith(".jar"))lib=p.getLogisimFile().getLoader().loadJarLibrary(file,str(a,"class_name"));else throw new IllegalArgumentException("Expected .circ or .jar");if(lib==null)throw new IllegalStateException("Library load failed");p.doAction(LogisimFileActions.loadLibrary(lib));return value(lib);}Library lib=p.getLogisimFile().getLibrary(str(a,"name"));if(lib==null)throw new IllegalArgumentException("Unknown library");if(action.equals("unload")){String why=p.getLogisimFile().getUnloadLibraryMessage(lib);if(why!=null)throw new IllegalArgumentException(why);p.doAction(LogisimFileActions.unloadLibrary(lib));}else if(action.equals("reload")){if(!(lib instanceof LoadedLibrary))throw new IllegalArgumentException("Not a loaded library");p.getLogisimFile().getLoader().reload((LoadedLibrary)lib);}else throw new IllegalArgumentException("Unknown library action");return map("action",action,"library",lib.getName());}
  if(op.equals("substate")){String action=str(a,"action");if(action.equals("enter")){Component cp=comp(p,str(a,"id"));if(!(cp.getFactory() instanceof SubcircuitFactory))throw new IllegalArgumentException("Not a subcircuit");p.setCircuitState(((SubcircuitFactory)cp.getFactory()).getSubstate(state,cp));}else if(action.equals("parent")){if(state.getParentState()==null)throw new IllegalArgumentException("Already root");p.setCircuitState(state.getParentState());}else throw new IllegalArgumentException("Unknown action");return value(p.getCircuitState());}
  if(op.equals("menu_list")){List<Object> items=new ArrayList<>();JMenuBar bar=p.getFrame().getJMenuBar();for(int i=0;i<bar.getMenuCount();i++)menuWalk(bar.getMenu(i),""+i,items);return items;}
  if(op.equals("menu_invoke")){String id=str(a,"item");Object item=object(id);if(!(item instanceof JMenuItem))throw new IllegalArgumentException("Expected menu item ref");JMenuItem button=(JMenuItem)item;if(!button.isEnabled())throw new IllegalArgumentException("Menu disabled");SwingUtilities.invokeLater(()->button.doClick());return map("queued",button.getText(),"completion","Observe application before next dependent operation");}
  if(op.equals("log_create")){Object log=invoke(p.getLogFrame(true),"getModel",new Class[]{});logs.put(ref(log),log);return value(log);}
  if(op.equals("log_select")){Object log=object(str(a,"log"));Object selection=invoke(log,"getSelection",new Class[]{});for(String id:(List<String>)a.get("components")){Component cp=comp(p,id);Class klass=Class.forName("com.cburch.logisim.gui.log.SelectionItem");Constructor ctor=klass.getDeclaredConstructors()[0];ctor.setAccessible(true);Object item=ctor.newInstance(log,new Component[0],cp,a.get("option"));invoke(selection,"add",new Class[]{klass},item);}return value(selection);}
  if(op.equals("log_sample")){Object log=object(str(a,"log"));invoke(log,"propagationCompleted",new Class[]{});Object selection=invoke(log,"getSelection",new Class[]{});int n=((Number)invoke(selection,"size",new Class[]{})).intValue();List<Object> result=new ArrayList<>();for(int i=0;i<n;i++){Object item=invoke(selection,"get",new Class[]{int.class},i);result.add(map("name",item.toString(),"value",value(invoke(item,"fetchValue",new Class[]{CircuitState.class},state))));}return result;}
  if(op.equals("log_file")){Object log=object(str(a,"log"));if(a.containsKey("path"))invoke(log,"setFile",new Class[]{File.class},path(str(a,"path"),true));invoke(log,"setFileHeader",new Class[]{boolean.class},bool(a,"header",true));invoke(log,"setFileEnabled",new Class[]{boolean.class},bool(a,"enabled",false));return map("enabled",invoke(log,"isFileEnabled",new Class[]{}),"file",String.valueOf(invoke(log,"getFile",new Class[]{})));}
  throw new IllegalArgumentException("Unknown operation "+op);
 }
 static void menuWalk(JMenuItem item,String path,List<Object> out){if(item==null)return;out.add(map("ref",ref(item),"path",path,"text",item.getText(),"enabled",item.isEnabled(),"selected",item.isSelected(),"class",item.getClass().getName()));if(item instanceof JMenu){JMenu m=(JMenu)item;for(int i=0;i<m.getItemCount();i++)menuWalk(m.getItem(i),path+"/"+i,out);}}
 static Object widget(java.awt.Component cp,int depth,int maxDepth){Map out=(Map)map("ref",ref(cp),"class",cp.getClass().getName(),"visible",cp.isVisible(),"enabled",cp.isEnabled());if(cp instanceof java.awt.Frame)out.put("title",((java.awt.Frame)cp).getTitle());if(cp instanceof java.awt.Dialog)out.put("title",((java.awt.Dialog)cp).getTitle());if(cp instanceof AbstractButton)out.put("text",((AbstractButton)cp).getText());if(cp instanceof JLabel)out.put("text",((JLabel)cp).getText());if(cp instanceof javax.swing.text.JTextComponent)out.put("text",((javax.swing.text.JTextComponent)cp).getText());if(cp instanceof JComboBox){JComboBox b=(JComboBox)cp;List<Object> items=new ArrayList<>();for(int i=0;i<b.getItemCount();i++)items.add(String.valueOf(b.getItemAt(i)));out.put("items",items);out.put("selected",b.getSelectedIndex());}if(cp instanceof JTabbedPane){JTabbedPane b=(JTabbedPane)cp;List<Object> items=new ArrayList<>();for(int i=0;i<b.getTabCount();i++)items.add(b.getTitleAt(i));out.put("tabs",items);out.put("selected",b.getSelectedIndex());}if(cp instanceof java.awt.Container&&depth<maxDepth){List<Object> children=new ArrayList<>();for(java.awt.Component child:((java.awt.Container)cp).getComponents())if(child.isVisible())children.add(widget(child,depth+1,maxDepth));out.put("children",children);}return out;}
 static boolean allowed(Class c){String n=c.getName();return n.startsWith("com.cburch.");}
 static Class klass(String name)throws ClassNotFoundException{if(!name.startsWith("com.cburch."))throw new IllegalArgumentException("Only com.cburch classes can be constructed or accessed statically");Class c=Class.forName(name,false,Workbench.class.getClassLoader());return c;}
 static Object argument(Object raw,Class type)throws Exception{
  if(raw==null)return null;
  if(raw instanceof Map&&((Map)raw).containsKey("ref")){Object o=object(str((Map)raw,"ref"));if(!type.isInstance(o))throw new IllegalArgumentException("Handle type mismatch: expected "+type.getName());return o;}
  if(type==Object.class)return raw;
  if(type==String.class)return raw.toString();if(type==boolean.class||type==Boolean.class)return raw;
  if(type==char.class||type==Character.class)return raw.toString().charAt(0);
  if(raw instanceof Number){Number n=(Number)raw;if(type==int.class||type==Integer.class)return n.intValue();if(type==long.class||type==Long.class)return n.longValue();if(type==double.class||type==Double.class)return n.doubleValue();if(type==float.class||type==Float.class)return n.floatValue();if(type==short.class)return n.shortValue();if(type==byte.class)return n.byteValue();}
  if(type==File.class)return path(raw.toString(),false);
  if(type.isArray()&&raw instanceof List){List list=(List)raw;Object arr=Array.newInstance(type.getComponentType(),list.size());for(int i=0;i<list.size();i++)Array.set(arr,i,argument(list.get(i),type.getComponentType()));return arr;}
  if(Collection.class.isAssignableFrom(type)&&raw instanceof List){Collection out=Set.class.isAssignableFrom(type)?new LinkedHashSet():new ArrayList();for(Object x:(List)raw)out.add(x instanceof Map&&((Map)x).containsKey("ref")?object(str((Map)x,"ref")):x);return out;}
  if(Map.class.isAssignableFrom(type)&&raw instanceof Map)return raw;
  throw new IllegalArgumentException("Use an object ref or matching primitive for "+type.getName());
 }
 static Object api(Map a)throws Exception {
  String op=str(a,"op");
  if(op.equals("api_describe")){
   Object target=a.containsKey("ref")?object(str(a,"ref")):klass(str(a,"class"));Class c=target instanceof Class?(Class)target:target.getClass();
   if(!allowed(c)&&!(target instanceof JMenuItem))throw new IllegalArgumentException("Only native Logisim objects may be invoked");
   String filter=(String)a.getOrDefault("filter","");List<Object> ms=new ArrayList<>(),fs=new ArrayList<>(),ctors=new ArrayList<>();
   for(Class k=c;k!=null&&allowed(k);k=k.getSuperclass()){
    for(Method m:k.getDeclaredMethods())if(!m.isSynthetic()&&m.getName().contains(filter)){String key=m.toGenericString();methods.put(key,m);ms.add(map("id",key,"name",m.getName(),"static",Modifier.isStatic(m.getModifiers()),"parameters",names(m.getParameterTypes()),"returns",m.getReturnType().getName(),"public",Modifier.isPublic(m.getModifiers())));}
    for(Field f:k.getDeclaredFields())if(!f.isSynthetic()&&f.getName().contains(filter)){String key=f.toGenericString();fields.put(key,f);fs.add(map("id",key,"name",f.getName(),"type",f.getType().getName(),"static",Modifier.isStatic(f.getModifiers()),"final",Modifier.isFinal(f.getModifiers())));}
   }
   for(Constructor ctor:c.getDeclaredConstructors())if(!ctor.isSynthetic()){String key=ctor.toGenericString();methods.put(key,ctor);ctors.add(map("id",key,"parameters",names(ctor.getParameterTypes())));}
   return map("class",c.getName(),"methods",ms,"fields",fs,"constructors",ctors,"note","Discovered API availability is not a behavioral test; inspect signatures before invocation");
  }
  if(op.equals("api_call")||op.equals("api_construct")){Executable executable=methods.get(str(a,"method"));if(executable==null)throw new IllegalArgumentException("Discover exact signature with api_describe first");List args=(List)a.getOrDefault("args",Collections.emptyList());Class[] types=executable.getParameterTypes();if(args.size()!=types.length)throw new IllegalArgumentException("Argument count mismatch");Object[] converted=new Object[types.length];for(int i=0;i<types.length;i++)converted[i]=argument(args.get(i),types[i]);executable.setAccessible(true);Object result;if(executable instanceof Constructor)result=((Constructor)executable).newInstance(converted);else{Method m=(Method)executable;Object target=Modifier.isStatic(m.getModifiers())?null:object(str(a,"ref"));result=m.invoke(target,converted);}return value(result);}
  if(op.equals("api_field")||op.equals("api_field_set")){Field f=fields.get(str(a,"field"));if(f==null)throw new IllegalArgumentException("Discover field first");f.setAccessible(true);Object target=Modifier.isStatic(f.getModifiers())?null:object(str(a,"ref"));if(op.equals("api_field_set")){if(Modifier.isFinal(f.getModifiers()))throw new IllegalArgumentException("Final fields cannot be changed");f.set(target,argument(a.get("value"),f.getType()));}return value(f.get(target));}
  if(op.equals("api_items")){Object obj=object(str(a,"ref"));int offset=integer(a,"offset",0),limit=integer(a,"limit",100);if(offset<0||limit<1||limit>1000)throw new IllegalArgumentException("Invalid pagination");List<Object> out=new ArrayList<>();int size;if(obj.getClass().isArray()){size=Array.getLength(obj);for(int i=offset;i<Math.min(size,offset+limit);i++)out.add(value(Array.get(obj,i)));}else if(obj instanceof Collection){List list=new ArrayList((Collection)obj);size=list.size();for(int i=offset;i<Math.min(size,offset+limit);i++)out.add(value(list.get(i)));}else if(obj instanceof Map){List<Map.Entry> list=new ArrayList(((Map)obj).entrySet());size=list.size();for(int i=offset;i<Math.min(size,offset+limit);i++)out.add(map("key",value(list.get(i).getKey()),"value",value(list.get(i).getValue())));}else throw new IllegalArgumentException("Handle is not array, collection or map");return map("total",size,"offset",offset,"items",out);}
  if(op.equals("api_release")){for(String id:(List<String>)a.get("refs")){Object o=objects.remove(id);if(o!=null)handles.remove(o);}return true;}
  throw new IllegalArgumentException("Unknown API action");
 }
 static List<String> names(Class[] classes){List<String> out=new ArrayList<>();for(Class c:classes)out.add(c.getName());return out;}
 static class Json {
  String s;int p;Json(String s){this.s=s;}static Object parse(String s){Json j=new Json(s);Object v=j.read();j.space();if(j.p!=s.length())throw new IllegalArgumentException("Trailing JSON data");return v;}
  void space(){while(p<s.length()&&Character.isWhitespace(s.charAt(p)))p++;}
  Object read(){space();if(p>=s.length())throw new IllegalArgumentException("Unexpected EOF");char c=s.charAt(p++);if(c=='"')return string();if(c=='{'){Map<String,Object> m=new LinkedHashMap<>();space();if(s.charAt(p)=='}'){p++;return m;}while(true){space();if(s.charAt(p++)!='"')throw new IllegalArgumentException("JSON key expected");String k=string();space();if(s.charAt(p++)!=':')throw new IllegalArgumentException("Colon expected");m.put(k,read());space();char end=s.charAt(p++);if(end=='}')return m;if(end!=',')throw new IllegalArgumentException("Comma expected");}}if(c=='['){List<Object> a=new ArrayList<>();space();if(s.charAt(p)==']'){p++;return a;}while(true){a.add(read());space();char end=s.charAt(p++);if(end==']')return a;if(end!=',')throw new IllegalArgumentException("Comma expected");}}int start=p-1;while(p<s.length()&&",]} \r\n\t".indexOf(s.charAt(p))<0)p++;String word=s.substring(start,p);if(word.equals("true"))return true;if(word.equals("false"))return false;if(word.equals("null"))return null;if(word.contains(".")||word.contains("e")||word.contains("E"))return Double.parseDouble(word);return Long.parseLong(word);}
  String string(){StringBuilder b=new StringBuilder();while(p<s.length()){char c=s.charAt(p++);if(c=='"')return b.toString();if(c=='\\'){char e=s.charAt(p++);if(e=='u'){b.append((char)Integer.parseInt(s.substring(p,p+4),16));p+=4;}else b.append(e=='n'?'\n':e=='r'?'\r':e=='t'?'\t':e=='b'?'\b':e=='f'?'\f':e);}else b.append(c);}throw new IllegalArgumentException("Unterminated string");}
  static String write(Object o){if(o==null)return "null";if(o instanceof Boolean||o instanceof Number)return o.toString();if(o instanceof Map){StringBuilder b=new StringBuilder("{");boolean comma=false;for(Object entry:((Map)o).entrySet()){Map.Entry e=(Map.Entry)entry;if(comma)b.append(',');comma=true;b.append(write(String.valueOf(e.getKey()))).append(':').append(write(e.getValue()));}return b.append('}').toString();}if(o instanceof Iterable){StringBuilder b=new StringBuilder("[");boolean comma=false;for(Object v:(Iterable)o){if(comma)b.append(',');comma=true;b.append(write(v));}return b.append(']').toString();}StringBuilder b=new StringBuilder("\"");for(char c:o.toString().toCharArray()){if(c=='"'||c=='\\')b.append('\\').append(c);else if(c=='\n')b.append("\\n");else if(c=='\r')b.append("\\r");else if(c=='\t')b.append("\\t");else if(c<32)b.append(String.format("\\u%04x",(int)c));else b.append(c);}return b.append('"').toString();}
 }
}
